// react-zustand/src/component/donation-button.tsx
// import { useCartContext } from "@/app/store/cart-context";

import { useCartStore } from "@/store/cart-store";

export const DonateButton = () => {
  const { addDonate } = useCartStore();

  const handleClick = () => {
    addDonate();
  };

  return <button onClick={handleClick}>Add $10 Donate</button>;
};

// vue-pinia/src/component/donation-button.vue
<template>
    <button @click="handleClick">Add $10 Donate</button>
  </template>
  
  <script>
//   import { addDonate, store } from "@/store/store";
  
//   export default {
//     name: "DonateButton",
//     setup() {
//       const handleClick = () => {
//         store.dispatch(addDonate(10));
//       };
  
//       return {
//         handleClick,
//       };
//     },
//   };
  </script>
  
  <style scoped>
  /* Add any necessary styles here */
  </style>
