// vue-pinia/src/component/donation-button.vue
<template>
    <button @click="handleClick">Add $10 Donate</button>
  </template>
  
  <script>
//   import { addDonate, store } from "@/store/store";
  
//   export default {
//     name: "DonateButton",
//     setup() {
//       const handleClick = () => {
//         store.dispatch(addDonate(10));
//       };
  
//       return {
//         handleClick,
//       };
//     },
//   };
  </script>
  
  <style scoped>
  /* Add any necessary styles here */
  </style>

// react-contextapi-flux-pattern/src/component/donation-button.tsx
// import { useCartContext } from "@/app/store/cart-context";

import { addDonate } from "@/store/cart-store/cart.action";
import { useStore } from "@/store/store";

export const DonateButton = () => {
  const { dispatch } = useStore();

  const handleClick = () => {
    dispatch(addDonate({ name: "Donate", price: 10 }));
  };

  return <button onClick={handleClick}>Add $10 Donate</button>;
};
