// react-prop-drilling-renders-v2/src/component/product-button.tsx
import { Item } from "./cart";

type ProductButtonProps = {
  label: string;
  price: number;
  onClick?: (item: Item) => void;
};

export const ProductButton = ({
  label,
  price,
  onClick,
}: ProductButtonProps) => {
  return (
    <div style={{ display: "flex", gap: 16 }}>
      <p>{label}</p>
      <p>Price: ${price}</p>
      <button
        onClick={() => {
          onClick && onClick({ label, price });
        }}
      >
        Add
      </button>
    </div>
  );
};

// vue-reactive-prop-drilling/src/component/product-button.vue
<template>
  <div style="display: flex; gap: 16px">
    <p>{{ label }}</p>
    <p>Price: ${{ price }}</p>
    <button @click="handleClick">Add</button>
  </div>
</template>

<script>
export default {
  name: "ProductButton",
  props: {
    label: {
      type: String,
      required: true,
    },
    price: {
      type: Number,
      required: true,
    },
    onClick: {
      type: Function,
      default: null,
    },
  },
  setup(props) {
    const handleClick = () => {
      if (props.onClick) {
        props.onClick(props.label, props.price);
      }
    };

    return {
      handleClick,
    };
  },
};
</script>

<style scoped>
/* Add any necessary styles here */
</style>
